export const LOGIN = 'LOGIN';

export const SYLLABUS_CHOOSE = 'SYLLABUS_CHOOSE';
export const TOPIC_CHOOSE = 'TOPIC_CHOOSE';

export const SYLLABI_FETCH_REQUEST = 'SYLLABI_FETCH_REQUEST';
export const SYLLABI_FETCH_SUCCESS = 'SYLLABI_FETCH_SUCCESS';
export const TOPICS_FETCH_REQUEST = 'TOPICS_FETCH_REQUEST';
export const TOPICS_FETCH_SUCCESS = 'TOPICS_FETCH_SUCCESS';



export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';